title: mofei log
name: "mofei Tech Blog"
author: Yang Lu
baseurl: "/log"
description: Document learning notes.
profile_url: "http://mofeilu.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
